"use client";

import { CircleAlert, MapPin, Plus, Store, Truck } from "lucide-react";
import { useEffect, useState } from "react";
import { Toggle } from "@/components/ui/toggle";
import { DAYS } from "@/features/menu/menu-model";

export function BusinessSettings({ businessName, locationName, orderingOpen, onOrderingToggle, dirty, onDirtyChange, onSaved }: { businessName: string; locationName: string; orderingOpen: boolean; onOrderingToggle: () => void; dirty: boolean; onDirtyChange: (dirty: boolean) => void; onSaved: (section: string) => void }) {
  const [loading, setLoading] = useState(true);
  const [activeSection, setActiveSection] = useState("general");
  const [orderType, setOrderType] = useState("both");
  const [taxRate, setTaxRate] = useState("18%");
  const [allowClosed, setAllowClosed] = useState(false);
  const [hours, setHours] = useState(DAYS.map((day, index) => ({ day, open: index !== 0, start: "08:00", end: "22:30" })));
  const [zones, setZones] = useState([{ id: "local", name: "Mandrem & Ashvem", min: 0, max: 5, fee: 35, freeAt: 650, minimum: 0, cost: 24, active: true }, { id: "nearby", name: "Arambol", min: 5, max: 12, fee: 60, freeAt: 900, minimum: 0, cost: 42, active: true }]);
  const [zoneError, setZoneError] = useState("");
  const sections = [["general", "General"], ["ordering", "Ordering"], ["hours", "Opening Hours"], ["tax", "Tax"], ["delivery", "Delivery"], ["commercials", "Commercials"]];
  const markDirty = () => onDirtyChange(true);
  const save = (section: string) => { if (section === "delivery") { const invalid = zones.some((zone) => zone.min >= zone.max) || zones.some((zone, index) => zones.some((other, otherIndex) => index !== otherIndex && zone.min < other.max && other.min < zone.max)); if (invalid) { setZoneError("Distance ranges cannot overlap. Adjust the zone boundaries, then save again."); return; } setZoneError(""); } onDirtyChange(false); onSaved(section); };
  const updateZone = (id: string, key: string, value: string | number | boolean) => { setZones((current) => current.map((zone) => zone.id === id ? { ...zone, [key]: value } : zone)); setZoneError(""); markDirty(); };
  const input = (label: string, value: string, type = "text") => <label className="field-label">{label}<input type={type} defaultValue={value} onChange={markDirty} /></label>;
  useEffect(() => { const timer = window.setTimeout(() => setLoading(false), 320); return () => window.clearTimeout(timer); }, []);
  if (loading) return <div className="settings-page page"><div className="settings-loading"><span /><span /><span /><span /></div></div>;
  return <div className="settings-page page">
    <div className="settings-context"><span><Store size={16} />Settings for <strong>{locationName}</strong></span></div>
    <div className="settings-layout">
      <nav className="settings-nav" aria-label="Business settings sections">{sections.map(([id, label]) => <button key={id} className={activeSection === id ? "active" : ""} onClick={() => { setActiveSection(id); document.getElementById(`settings-${id}`)?.scrollIntoView({ behavior: "smooth", block: "start" }); }}>{label}</button>)}</nav>
      <main className="settings-content">
        <section id="settings-general" className="settings-section"><div className="settings-section-head"><div><h2>General</h2><p>Business information shown to customers and staff for this outlet.</p></div></div><div className="settings-grid">{input("Business name", businessName)}{input("Location / outlet name", locationName)}{input("Contact phone", "+91 94490 76076", "tel")}<label className="field-label settings-full">Address<textarea defaultValue="House 14, Palm Grove Lane" onChange={markDirty} rows={2} /></label>{input("Locality", "Mandrem")}{input("City", "North Goa")}{input("State", "Goa")}{input("PIN code", "403527")}</div><div className="map-location"><MapPin size={18} /><span><strong>Restaurant map location</strong><small>Mandrem Beach Road, Goa</small></span><button className="secondary-button compact-button" onClick={markDirty}>Search address</button><button className="text-button" onClick={markDirty}>Use current location</button></div><div className="section-save"><button className="primary-button" onClick={() => save("General")}>Save changes</button></div></section>
        <section id="settings-ordering" className="settings-section"><div className="settings-section-head"><div><h2>Ordering</h2><p>Choose how customers can place online orders from this outlet.</p></div></div><div className="operational-setting"><span><strong>Accepting orders</strong><small>Temporarily stop customers from placing new online orders.</small></span><div><span className={orderingOpen ? "available-text" : "unavailable-text"}>{orderingOpen ? "On" : "Off"}</span><Toggle checked={orderingOpen} onChange={onOrderingToggle} label="Toggle accepting orders" /></div></div><div className="settings-grid"><label className="field-label settings-full">Order types<div className="choice-row">{[["delivery", "Delivery"], ["pickup", "Pickup"], ["both", "Delivery & Pickup"]].map(([id,label]) => <button key={id} type="button" className={orderType === id ? "selected" : ""} onClick={() => { setOrderType(id); markDirty(); }}>{label}</button>)}</div></label><label className="field-label currency-field">Minimum order value<span><b>₹</b><input type="number" min="0" step="0.01" defaultValue="200" onChange={markDirty} /></span><small>Applied at checkout.</small></label><label className="field-label">Default preparation time<input type="number" min="1" defaultValue="25" onChange={markDirty} /><small>Minutes. Product-level timing takes priority when set.</small></label></div><label className="settings-toggle-line"><input type="checkbox" checked={allowClosed} onChange={(event) => { setAllowClosed(event.target.checked); markDirty(); }} /><span><strong>Allow orders when closed</strong><small>Customers can order for a later fulfilment window.</small></span></label><div className="section-save"><button className="primary-button" onClick={() => save("Ordering")}>Save changes</button></div></section>
        <section id="settings-hours" className="settings-section"><div className="settings-section-head"><div><h2>Opening Hours</h2><p>Weekly outlet hours in Asia/Kolkata.</p></div></div><div className="hours-editor">{hours.map((row, index) => <div className="hours-row" key={row.day}><strong>{row.day}</strong><Toggle checked={row.open} onChange={() => { setHours((current) => current.map((item, itemIndex) => itemIndex === index ? { ...item, open: !item.open } : item)); markDirty(); }} label={`${row.day} open`} />{row.open ? <><input type="time" value={row.start} onChange={(event) => { setHours((current) => current.map((item, itemIndex) => itemIndex === index ? { ...item, start: event.target.value } : item)); markDirty(); }} /><span>to</span><input type="time" value={row.end} onChange={(event) => { setHours((current) => current.map((item, itemIndex) => itemIndex === index ? { ...item, end: event.target.value } : item)); markDirty(); }} /></> : <span className="closed-label">Closed</span>}</div>)}</div><div className="section-save"><button className="primary-button" onClick={() => save("Opening hours")}>Save changes</button></div></section>
        <section id="settings-tax" className="settings-section"><div className="settings-section-head"><div><h2>Tax</h2><p>Applied automatically to eligible orders.</p></div></div><div className="tax-options">{["0%", "5%", "12%", "18%", "28%"].map((rate) => <button key={rate} className={taxRate === rate ? "selected" : ""} onClick={() => { setTaxRate(rate); markDirty(); }}>{rate}</button>)}</div><div className="section-save"><button className="primary-button" onClick={() => save("Tax")}>Save changes</button></div></section>
        <section id="settings-delivery" className="settings-section"><div className="settings-section-head"><div><h2>Delivery</h2><p>Set customer charges and coverage by distance from this outlet.</p></div><button className="secondary-button compact-button" onClick={() => { setZones((current) => [...current, { id: `zone-${Date.now()}`, name: "New zone", min: 12, max: 18, fee: 0, freeAt: 0, minimum: 0, cost: 0, active: true }]); markDirty(); }}><Plus size={15} />Add zone</button></div>{zones.length ? <div className="delivery-zones">{zones.map((zone, index) => <div className="delivery-zone" key={zone.id}><div className="zone-number">{index + 1}</div><div className="zone-fields"><label className="field-label">Zone name<input value={zone.name} onChange={(event) => updateZone(zone.id, "name", event.target.value)} /></label><label className="field-label">Distance range<div className="range-fields"><input type="number" value={zone.min} onChange={(event) => updateZone(zone.id, "min", Number(event.target.value))} /><span>to</span><input type="number" value={zone.max} onChange={(event) => updateZone(zone.id, "max", Number(event.target.value))} /><small>km</small></div></label><label className="field-label">Delivery fee<div className="currency-field"><span><b>₹</b><input type="number" value={zone.fee} onChange={(event) => updateZone(zone.id, "fee", Number(event.target.value))} /></span></div></label><label className="field-label">Free delivery at<div className="currency-field"><span><b>₹</b><input type="number" value={zone.freeAt} onChange={(event) => updateZone(zone.id, "freeAt", Number(event.target.value))} /></span></div></label><label className="field-label">Zone minimum <div className="currency-field"><span><b>₹</b><input type="number" value={zone.minimum} onChange={(event) => updateZone(zone.id, "minimum", Number(event.target.value))} /></span></div></label><label className="field-label">Estimated delivery cost<div className="currency-field"><span><b>₹</b><input type="number" value={zone.cost} onChange={(event) => updateZone(zone.id, "cost", Number(event.target.value))} /></span></div><small>Used to estimate delivery margin.</small></label></div><div className="zone-actions"><Toggle checked={zone.active} onChange={() => updateZone(zone.id, "active", !zone.active)} label={`${zone.name} active`} /><button className="destructive-link" onClick={() => { setZones((current) => current.filter((item) => item.id !== zone.id)); markDirty(); }}>Remove</button></div></div>)}</div> : <div className="empty-state compact-empty"><Truck size={26} /><h3>No delivery zones</h3><p>Add a distance range to start offering delivery.</p></div>}{zoneError && <p className="field-error">{zoneError}</p>}<div className="section-save"><button className="primary-button" onClick={() => save("Delivery")}>Save changes</button></div></section>
        <section id="settings-commercials" className="settings-section"><div className="settings-section-head"><div><h2>Commercials</h2><p>Read-only agreement details for this business.</p></div></div><div className="commercials-grid"><div><span>Platform commission</span><strong>8%</strong><small>Applied to eligible direct-order revenue according to your agreement.</small></div><div><span>Aggregator benchmark</span><strong>40%</strong><small>Used only to estimate aggregator fees avoided in analytics.</small></div></div><div className="managed-note"><CircleAlert size={16} /><span><strong>Managed by your account team</strong>Contact them to review these commercial terms.</span></div><div className="read-only-meta"><span>Currency <strong>INR</strong></span><span>Timezone <strong>Asia/Kolkata</strong></span></div></section>
      </main>
    </div>
    {dirty && <div className="settings-unsaved-bar"><span><span />Unsaved changes</span><button className="primary-button compact-button" onClick={() => save("Business")}>Save changes</button></div>}
  </div>;
}
