import type { StorefrontDemo } from "../domain/storefront";

export const a2MandremStorefront: StorefrontDemo = {
  venue: {
    businessName: "A2 Food & Beverages",
    displayName: "A2",
    locationName: "Mandrem, Goa",
    locationDescription: "Freshly made favourites, served from Mandrem.",
    address: "Mandrem Market Road, Mandrem, Goa 403527",
    orderingStatus: "Open today · Orders until 10:30 PM",
    accentColor: "#ad412d",
  },
  menu: {
    defaultPresentation: "list",
    allowPresentationChange: true,
    categories: [
      {
        id: "south-indian",
        name: "South Indian",
        description: "Breakfast classics, hot off the tawa.",
        imageUrl: "/food/masala-dosa.jpg",
      },
      {
        id: "goan-mains",
        name: "Goan mains",
        description: "Comforting coastal plates and curries.",
        imageUrl: "/food/goan-prawn-curry.jpg",
      },
      {
        id: "quick-bites",
        name: "Quick bites",
        description: "Easy, satisfying snacks for any time.",
        imageUrl: "/food/paneer-kathi-roll.jpg",
      },
      {
        id: "beverages",
        name: "Beverages",
        description: "Coolers, coffee and fresh pours.",
        imageUrl: "/food/kokum-cooler.jpg",
      },
      {
        id: "desserts",
        name: "Desserts",
        description: "A sweet finish from the Goan table.",
        imageUrl: "/food/bebinca.jpg",
      },
    ],
    products: [
      {
        id: "masala-dosa",
        categoryId: "south-indian",
        name: "Classic Masala Dosa",
        description: "Crisp dosa with a spiced potato filling, sambar and chutneys.",
        price: 150,
        imageUrl: "/food/masala-dosa.jpg",
        availability: "available",
        badges: ["Bestseller", "Vegetarian"],
      },
      {
        id: "ghee-roast",
        categoryId: "south-indian",
        name: "Ghee Roast Dosa",
        description: "Paper-thin roast dosa finished with fragrant ghee.",
        price: 165,
        imageUrl: "/food/masala-dosa.jpg",
        availability: "available",
        badges: ["Vegetarian"],
      },
      {
        id: "idli-vada-combo",
        categoryId: "south-indian",
        name: "Idli Vada Combo",
        description: "Steamed idlis and a crisp vada with sambar and chutneys.",
        price: 135,
        imageUrl: "/food/masala-dosa.jpg",
        availability: "available",
        badges: ["Vegetarian"],
      },
      {
        id: "prawn-curry-rice",
        categoryId: "goan-mains",
        name: "Goan Prawn Curry Rice",
        description: "Coastal prawn curry with steamed rice and a seasonal side.",
        price: 340,
        imageUrl: "/food/goan-prawn-curry.jpg",
        availability: "available",
        badges: ["Coastal favourite"],
      },
      {
        id: "veg-xacuti",
        categoryId: "goan-mains",
        name: "Vegetable Xacuti",
        description: "Garden vegetables in a roasted coconut and spice curry.",
        price: 260,
        imageUrl: "/food/goan-prawn-curry.jpg",
        availability: "available",
        badges: ["Vegetarian"],
      },
      {
        id: "fish-thali",
        categoryId: "goan-mains",
        name: "Goan Fish Thali",
        description: "A satisfying home-style Goan fish curry meal.",
        price: 390,
        imageUrl: "/food/goan-prawn-curry.jpg",
        availability: "sold-out",
        badges: ["Sold out"],
      },
      {
        id: "paneer-kathi-roll",
        categoryId: "quick-bites",
        name: "Paneer Kathi Roll",
        description: "Charred paneer, onions and chutney wrapped in a soft paratha.",
        price: 190,
        imageUrl: "/food/paneer-kathi-roll.jpg",
        availability: "available",
        badges: ["Vegetarian"],
      },
      {
        id: "veg-cutlet",
        categoryId: "quick-bites",
        name: "Crisp Vegetable Cutlet",
        description: "Golden vegetable cutlets with bright coriander chutney.",
        price: 145,
        imageUrl: "/food/paneer-kathi-roll.jpg",
        availability: "available",
        badges: ["Vegetarian"],
      },
      {
        id: "masala-fries",
        categoryId: "quick-bites",
        name: "Masala Fries",
        description: "Crisp fries dusted with house masala and lime.",
        price: 130,
        imageUrl: "/food/paneer-kathi-roll.jpg",
        availability: "available",
        badges: ["Vegetarian"],
      },
      {
        id: "kokum-cooler",
        categoryId: "beverages",
        name: "Kokum Cooler",
        description: "A bright, tangy Goan kokum cooler served chilled.",
        price: 95,
        imageUrl: "/food/kokum-cooler.jpg",
        availability: "available",
        badges: ["House special"],
      },
      {
        id: "filter-coffee",
        categoryId: "beverages",
        name: "South Indian Filter Coffee",
        description: "Rich, aromatic coffee with hot milk and a frothy pour.",
        price: 80,
        availability: "available",
      },
      {
        id: "bebinca",
        categoryId: "desserts",
        name: "Goan Bebinca",
        description: "A layered coconut milk dessert, gently caramelised.",
        price: 180,
        imageUrl: "/food/bebinca.jpg",
        availability: "available",
        badges: ["Goan classic"],
      },
      {
        id: "tender-coconut-pudding",
        categoryId: "desserts",
        name: "Tender Coconut Pudding",
        description: "Silky coconut pudding with a toasted jaggery crumble.",
        price: 160,
        imageUrl: "/food/bebinca.jpg",
        availability: "available",
        badges: ["Vegetarian"],
      },
    ],
    featuredProducts: [
      { productId: "masala-dosa", editorialLabel: "A Mandrem favourite" },
      { productId: "prawn-curry-rice", editorialLabel: "From the Goan table" },
      { productId: "kokum-cooler", editorialLabel: "Cool down" },
    ],
  },
};
