import type { CustomerProfile, DeliveryAddress, StorefrontDemo, StorefrontOrder } from "../domain/storefront";

export const a2MandremStorefront: StorefrontDemo = {
  venue: {
    businessName: "A2 Food & Beverages",
    displayName: "A2",
    locationName: "Mandrem, Goa",
    locationDescription: "Freshly made favourites, served from Mandrem.",
    address: "Mandrem Market Road, Mandrem, Goa 403527",
    orderingStatus: "Open today · Orders until 10:30 PM",
    isAcceptingOrders: true,
    accentColor: "#ad412d",
  },
  menu: {
    defaultPresentation: "list",
    allowPresentationChange: true,
    categories: [
      {
        id: "south-indian",
        name: "South Indian",
        description: "Breakfast classics, hot off the tawa.",
        imageUrl: "/food/masala-dosa.jpg",
      },
      {
        id: "goan-mains",
        name: "Goan mains",
        description: "Comforting coastal plates and curries.",
        imageUrl: "/food/goan-prawn-curry.jpg",
      },
      {
        id: "quick-bites",
        name: "Quick bites",
        description: "Easy, satisfying snacks for any time.",
        imageUrl: "/food/paneer-kathi-roll.jpg",
      },
      {
        id: "beverages",
        name: "Beverages",
        description: "Coolers, coffee and fresh pours.",
        imageUrl: "/food/kokum-cooler.jpg",
      },
      {
        id: "desserts",
        name: "Desserts",
        description: "A sweet finish from the Goan table.",
        imageUrl: "/food/bebinca.jpg",
      },
    ],
    products: [
      {
        id: "masala-dosa",
        categoryId: "south-indian",
        name: "Classic Masala Dosa",
        description: "Crisp dosa with a spiced potato filling, sambar and chutneys.",
        price: 150,
        imageUrl: "/food/masala-dosa.jpg",
        availability: "available",
        badges: ["Bestseller", "Vegetarian"],
      },
      {
        id: "ghee-roast",
        categoryId: "south-indian",
        name: "Ghee Roast Dosa",
        description: "Paper-thin roast dosa finished with fragrant ghee.",
        price: 165,
        imageUrl: "/food/masala-dosa.jpg",
        availability: "available",
        badges: ["Vegetarian"],
      },
      {
        id: "idli-vada-combo",
        categoryId: "south-indian",
        name: "Idli Vada Combo",
        description: "Steamed idlis and a crisp vada with sambar and chutneys.",
        price: 135,
        imageUrl: "/food/masala-dosa.jpg",
        availability: "available",
        badges: ["Vegetarian"],
      },
      {
        id: "prawn-curry-rice",
        categoryId: "goan-mains",
        name: "Goan Prawn Curry Rice",
        description: "Coastal prawn curry with steamed rice and a seasonal side.",
        price: 340,
        imageUrl: "/food/goan-prawn-curry.jpg",
        availability: "available",
        badges: ["Coastal favourite"],
      },
      {
        id: "veg-xacuti",
        categoryId: "goan-mains",
        name: "Vegetable Xacuti",
        description: "Garden vegetables in a roasted coconut and spice curry.",
        price: 260,
        imageUrl: "/food/goan-prawn-curry.jpg",
        availability: "available",
        badges: ["Vegetarian"],
      },
      {
        id: "fish-thali",
        categoryId: "goan-mains",
        name: "Goan Fish Thali",
        description: "A satisfying home-style Goan fish curry meal.",
        price: 390,
        imageUrl: "/food/goan-prawn-curry.jpg",
        availability: "sold-out",
        badges: ["Sold out"],
      },
      {
        id: "paneer-kathi-roll",
        categoryId: "quick-bites",
        name: "Paneer Kathi Roll",
        description: "Charred paneer, onions and chutney wrapped in a soft paratha.",
        price: 190,
        imageUrl: "/food/paneer-kathi-roll.jpg",
        availability: "available",
        badges: ["Vegetarian"],
      },
      {
        id: "veg-cutlet",
        categoryId: "quick-bites",
        name: "Crisp Vegetable Cutlet",
        description: "Golden vegetable cutlets with bright coriander chutney.",
        price: 145,
        imageUrl: "/food/paneer-kathi-roll.jpg",
        availability: "available",
        badges: ["Vegetarian"],
      },
      {
        id: "masala-fries",
        categoryId: "quick-bites",
        name: "Masala Fries",
        description: "Crisp fries dusted with house masala and lime.",
        price: 130,
        imageUrl: "/food/paneer-kathi-roll.jpg",
        availability: "available",
        badges: ["Vegetarian"],
      },
      {
        id: "kokum-cooler",
        categoryId: "beverages",
        name: "Kokum Cooler",
        description: "A bright, tangy Goan kokum cooler served chilled.",
        price: 95,
        imageUrl: "/food/kokum-cooler.jpg",
        availability: "available",
        badges: ["House special"],
      },
      {
        id: "filter-coffee",
        categoryId: "beverages",
        name: "South Indian Filter Coffee",
        description: "Rich, aromatic coffee with hot milk and a frothy pour.",
        price: 80,
        availability: "available",
      },
      {
        id: "bebinca",
        categoryId: "desserts",
        name: "Goan Bebinca",
        description: "A layered coconut milk dessert, gently caramelised.",
        price: 180,
        imageUrl: "/food/bebinca.jpg",
        availability: "available",
        badges: ["Goan classic"],
      },
      {
        id: "tender-coconut-pudding",
        categoryId: "desserts",
        name: "Tender Coconut Pudding",
        description: "Silky coconut pudding with a toasted jaggery crumble.",
        price: 160,
        imageUrl: "/food/bebinca.jpg",
        availability: "available",
        badges: ["Vegetarian"],
      },
    ],
    featuredProducts: [
      { productId: "masala-dosa", editorialLabel: "A Mandrem favourite" },
      { productId: "prawn-curry-rice", editorialLabel: "From the Goan table" },
      { productId: "kokum-cooler", editorialLabel: "Cool down" },
    ],
  },
};

export const a2MandremCustomer: CustomerProfile = {
  name: "Ashwin Babu",
  countryCode: "+91",
  phone: "9025117533",
  email: "ashwin@example.com",
  isPhoneVerified: true,
};

export const a2MandremAddresses: DeliveryAddress[] = [
  {
    id: "home-beach-road", label: "Home", recipientName: "Ashwin Babu", recipientPhone: "9025117533",
    line1: "41 Beach Road", line2: "", locality: "Arambol", city: "North Goa", state: "Goa", postalCode: "403524",
    landmark: "Near the beach entrance", instructions: "Leave at reception", isDefault: true,
  },
  {
    id: "work-mandrem", label: "Work", recipientName: "Ashwin Babu", recipientPhone: "9025117533",
    line1: "Mandrem Market Road", line2: "", locality: "Mandrem", city: "North Goa", state: "Goa", postalCode: "403527",
    landmark: "", instructions: "", isDefault: false,
  },
];

export const a2MandremOrders: StorefrontOrder[] = [
  {
    id: "A21083", restaurantId: "a2-mandrem", placedAt: "2026-08-14T15:20:00+05:30", status: "preparing",
    paymentStatus: "paid", paymentMethod: "UPI", fulfilment: "delivery",
    items: [
      { id: "order-1083-1", productId: "prawn-curry-rice", name: "Goan Prawn Curry Rice", quantity: 1, unitPrice: 340, selectedOptions: ["Medium spicy"] },
      { id: "order-1083-2", productId: "paneer-kathi-roll", name: "Paneer Kathi Roll", quantity: 1, unitPrice: 190 },
      { id: "order-1083-3", productId: "kokum-cooler", name: "Kokum Cooler", quantity: 1, unitPrice: 95 },
    ],
    subtotal: 625, discount: 0, deliveryFee: 39, taxes: 112, total: 776,
    deliveryAddress: a2MandremAddresses[0], orderNote: "Please call when outside.", estimatedFulfilment: "Estimated delivery 4:10 PM",
    timeline: [
      { label: "Order placed", occurredAt: "2026-08-14T15:20:00+05:30" },
      { label: "Accepted", occurredAt: "2026-08-14T15:22:00+05:30" },
      { label: "Preparing", occurredAt: "2026-08-14T15:28:00+05:30" },
    ],
  },
  {
    id: "A20984", restaurantId: "a2-mandrem", placedAt: "2026-08-12T20:42:00+05:30", status: "delivered",
    paymentStatus: "paid", paymentMethod: "UPI", fulfilment: "delivery",
    items: [
      { id: "order-984-1", productId: "masala-dosa", name: "Classic Masala Dosa", quantity: 2, unitPrice: 150, selectedOptions: ["Extra chutney"] },
      { id: "order-984-2", productId: "masala-fries", name: "Masala Fries", quantity: 1, unitPrice: 130, selectedOptions: ["Extra lime"] },
    ],
    subtotal: 430, discount: 50, couponCode: "SAVE10", deliveryFee: 39, taxes: 68, total: 487,
    deliveryAddress: a2MandremAddresses[0], completedAt: "2026-08-12T21:26:00+05:30",
    timeline: [
      { label: "Order placed", occurredAt: "2026-08-12T20:42:00+05:30" },
      { label: "Accepted", occurredAt: "2026-08-12T20:44:00+05:30" },
      { label: "Out for delivery", occurredAt: "2026-08-12T21:08:00+05:30" },
      { label: "Delivered", occurredAt: "2026-08-12T21:26:00+05:30" },
    ],
  },
  {
    id: "A20917", restaurantId: "a2-mandrem", placedAt: "2026-08-03T13:14:00+05:30", status: "completed",
    paymentStatus: "paid", paymentMethod: "Card", fulfilment: "pickup",
    items: [
      { id: "order-917-1", productId: "veg-xacuti", name: "Vegetable Xacuti", quantity: 1, unitPrice: 260 },
      { id: "order-917-2", productId: "bebinca", name: "Goan Bebinca", quantity: 1, unitPrice: 180 },
    ],
    subtotal: 440, discount: 0, deliveryFee: 0, taxes: 79, total: 519, completedAt: "2026-08-03T13:39:00+05:30",
    timeline: [
      { label: "Order placed", occurredAt: "2026-08-03T13:14:00+05:30" },
      { label: "Ready for pickup", occurredAt: "2026-08-03T13:36:00+05:30" },
      { label: "Collected", occurredAt: "2026-08-03T13:39:00+05:30" },
    ],
  },
  {
    id: "A20871", restaurantId: "a2-mandrem", placedAt: "2026-07-27T19:08:00+05:30", status: "cancelled",
    paymentStatus: "refunded", fulfilment: "delivery",
    items: [{ id: "order-871-1", productId: "fish-thali", name: "Goan Fish Thali", quantity: 1, unitPrice: 390 }],
    subtotal: 390, discount: 0, deliveryFee: 0, taxes: 0, total: 390,
    deliveryAddress: a2MandremAddresses[1], cancellationReason: "Restaurant unable to fulfil this order.",
    timeline: [
      { label: "Order placed", occurredAt: "2026-07-27T19:08:00+05:30" },
      { label: "Cancelled", occurredAt: "2026-07-27T19:14:00+05:30" },
    ],
  },
];
