-- Expands the notification matrix beyond order.placed/order.cancelled:
--   - order.cancelled -> staff_group (new) and business_owners (new, gated by
--     a per-business toggle)
--   - order.waiting_3m / order.waiting_8m -> staff_group / business_owners,
--     generated by a periodic scan (there is no domain-event trigger for
--     "time has passed", so this is the one capture path that isn't
--     trigger-based)
--   - store.paused / store.resumed -> staff_group and business_owners,
--     captured from the existing ordering_enabled flag
--   - sales.daily_summary -> business_owners only, generated once per
--     business-local day at ~23:00
--
-- All of these reuse the existing outbox (notifications.events /
-- notifications.deliveries) and dispatcher -- no parallel mechanism.

-- ---------------------------------------------------------------------------
-- 1. Widen notifications.events for the new event/entity types.
-- ---------------------------------------------------------------------------

alter table notifications.events drop constraint events_event_type_check;
alter table notifications.events add constraint events_event_type_check
  check (event_type in (
    'order.placed', 'order.cancelled', 'order.waiting_3m', 'order.waiting_8m',
    'store.paused', 'store.resumed', 'sales.daily_summary'
  ));

alter table notifications.events drop constraint events_entity_type_check;
alter table notifications.events add constraint events_entity_type_check
  check (entity_type in ('order', 'location'));

-- ---------------------------------------------------------------------------
-- 2. Per-business preference: whether cancellations also page the owner.
--    Everything else in this matrix is unconditional; this is the one row
--    the user explicitly wants a real on/off switch for.
-- ---------------------------------------------------------------------------

create table notifications.business_preferences (
  business_id uuid primary key references core.businesses(id),
  notify_owner_on_cancellation boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table notifications.business_preferences enable row level security;
revoke all on notifications.business_preferences from public;
revoke all on notifications.business_preferences from anon;
revoke all on notifications.business_preferences from authenticated;

create trigger business_preferences_set_updated_at
  before update on notifications.business_preferences
  for each row execute function private.set_updated_at();

create or replace function public.notifications_get_business_preferences(p_business_id uuid)
returns jsonb
language plpgsql
stable
security definer
set search_path to ''
as $function$
declare
  v_notify boolean;
begin
  if not (select auth.uid()) is not null
     or not (select private.can_manage_sensitive_business_configuration(p_business_id)) then
    raise exception using errcode = '42501', message = 'not authorized to view this business';
  end if;

  select bp.notify_owner_on_cancellation into v_notify
  from notifications.business_preferences bp where bp.business_id = p_business_id;

  return jsonb_build_object('notifyOwnerOnCancellation', coalesce(v_notify, false));
end;
$function$;

revoke all on function public.notifications_get_business_preferences(uuid) from public;
revoke all on function public.notifications_get_business_preferences(uuid) from anon;
grant execute on function public.notifications_get_business_preferences(uuid) to authenticated;

create or replace function public.notifications_set_business_preferences(
  p_business_id uuid,
  p_notify_owner_on_cancellation boolean
)
returns jsonb
language plpgsql
security definer
set search_path to ''
as $function$
begin
  if not (select auth.uid()) is not null
     or not (select private.can_manage_sensitive_business_configuration(p_business_id)) then
    raise exception using errcode = '42501', message = 'not authorized to manage this business';
  end if;

  insert into notifications.business_preferences (business_id, notify_owner_on_cancellation)
  values (p_business_id, p_notify_owner_on_cancellation)
  on conflict (business_id) do update
  set notify_owner_on_cancellation = excluded.notify_owner_on_cancellation;

  return jsonb_build_object('notifyOwnerOnCancellation', p_notify_owner_on_cancellation);
end;
$function$;

revoke all on function public.notifications_set_business_preferences(uuid, boolean) from public;
revoke all on function public.notifications_set_business_preferences(uuid, boolean) from anon;
grant execute on function public.notifications_set_business_preferences(uuid, boolean) to authenticated;

-- ---------------------------------------------------------------------------
-- 3. Extend the order-context RPC with business_owners destinations and the
--    cancellation preference, so recipient resolution stays a pure read of
--    the planning context (no new query-per-rule).
-- ---------------------------------------------------------------------------

create or replace function public.notifications_get_order_context(p_order_id uuid)
returns jsonb
language plpgsql
stable
security definer
set search_path to ''
as $function$
declare
  v_order ordering.orders%rowtype;
  v_business core.businesses%rowtype;
  v_location core.business_locations%rowtype;
  v_customer core.customers%rowtype;
  v_items jsonb;
  v_payment jsonb;
  v_refund_total numeric;
  v_refund_status text;
  v_staff_group notifications.telegram_destinations%rowtype;
  v_owners jsonb;
  v_notify_owner_on_cancellation boolean;
begin
  if not (select private.request_is_service_role()) then
    raise exception using errcode = '42501', message = 'service role required';
  end if;

  select o.* into v_order from ordering.orders o where o.id = p_order_id;
  if not found then
    raise exception using errcode = 'P0002', message = 'order not found';
  end if;

  select b.* into v_business from core.businesses b where b.id = v_order.business_id;
  select l.* into v_location from core.business_locations l where l.id = v_order.location_id;

  if v_order.customer_id is not null then
    select c.* into v_customer from core.customers c where c.id = v_order.customer_id;
  end if;

  select coalesce(jsonb_agg(jsonb_build_object(
    'productName', oi.product_name,
    'quantity', oi.quantity,
    'baseUnitPrice', oi.base_unit_price::text,
    'modifierUnitTotal', oi.modifier_unit_total::text,
    'finalUnitPrice', oi.final_unit_price::text,
    'lineTotal', oi.line_total::text,
    'customerNote', oi.customer_note,
    'options', (
      select coalesce(jsonb_agg(jsonb_build_object(
        'optionGroupName', oio.option_group_name,
        'optionName', oio.option_name,
        'priceDelta', oio.price_delta::text,
        'quantity', oio.quantity
      ) order by oio.option_group_name, oio.option_name), '[]'::jsonb)
      from ordering.order_item_options oio
      where oio.order_item_id = oi.id
    )
  ) order by oi.created_at), '[]'::jsonb)
  into v_items
  from ordering.order_items oi
  where oi.order_id = v_order.id;

  select jsonb_build_object(
    'status', p.status,
    'method', p.method,
    'amount', p.amount::text,
    'paidAt', p.paid_at
  )
  into v_payment
  from ordering.payments p
  where p.order_id = v_order.id
  order by p.created_at desc
  limit 1;

  select coalesce(sum(r.amount) filter (where r.status = 'completed'), 0)
  into v_refund_total
  from ordering.refunds r
  where r.order_id = v_order.id;

  select r.status into v_refund_status
  from ordering.refunds r
  where r.order_id = v_order.id
  order by r.created_at desc
  limit 1;

  select * into v_staff_group
  from notifications.telegram_destinations d
  where d.business_id = v_order.business_id
    and d.location_id = v_order.location_id
    and d.destination_type = 'staff_group'
    and d.is_active
  limit 1;

  select coalesce(jsonb_agg(jsonb_build_object('chatId', d.telegram_chat_id)), '[]'::jsonb)
  into v_owners
  from notifications.telegram_destinations d
  join core.business_users bu on bu.id = d.business_user_id
  where d.destination_type = 'business_user'
    and d.is_active
    and bu.business_id = v_order.business_id
    and bu.is_active
    and bu.role in ('owner', 'admin');

  select bp.notify_owner_on_cancellation into v_notify_owner_on_cancellation
  from notifications.business_preferences bp where bp.business_id = v_order.business_id;

  return jsonb_build_object(
    'order', jsonb_build_object(
      'id', v_order.id,
      'orderNumber', v_order.order_number,
      'businessId', v_order.business_id,
      'locationId', v_order.location_id,
      'customerId', v_order.customer_id,
      'fulfillmentType', v_order.fulfillment_type,
      'status', v_order.status,
      'paymentStatus', v_order.payment_status,
      'paymentMethod', v_order.payment_method,
      'currency', v_order.currency,
      'foodSubtotal', v_order.food_subtotal::text,
      'discountTotal', v_order.discount_total::text,
      'taxTotal', v_order.tax_total::text,
      'deliveryFee', v_order.delivery_fee::text,
      'grandTotal', v_order.grand_total::text,
      'customerNameSnapshot', v_order.customer_name_snapshot,
      'customerPhoneSnapshot', v_order.customer_phone_snapshot,
      'deliveryAddressSnapshot', v_order.delivery_address_snapshot,
      'customerNote', v_order.customer_note,
      'placedAt', v_order.placed_at,
      'acceptedAt', v_order.accepted_at,
      'outForDeliveryAt', v_order.out_for_delivery_at,
      'deliveredAt', v_order.delivered_at,
      'cancelledAt', v_order.cancelled_at,
      'cancelReason', v_order.cancel_reason,
      'estimatedDeliveryMinutes', v_order.estimated_delivery_minutes,
      'couponCodeSnapshot', v_order.coupon_code_snapshot,
      'couponDiscountAmount', v_order.coupon_discount_amount::text
    ),
    'items', v_items,
    'business', jsonb_build_object(
      'id', v_business.id,
      'name', v_business.name,
      'logoUrl', v_business.logo_url,
      'timezone', v_business.timezone,
      'currency', v_business.currency
    ),
    'location', jsonb_build_object(
      'id', v_location.id,
      'name', v_location.name,
      'phone', v_location.phone,
      'addressLine', nullif(trim(both ', ' from
        coalesce(v_location.address_line_1, '') ||
        case when v_location.address_line_2 is not null and v_location.address_line_2 <> ''
          then ', ' || v_location.address_line_2 else '' end ||
        ', ' || coalesce(v_location.city, '')
      ), ''),
      'storefrontDomain', v_location.storefront_domain
    ),
    'customer', case when v_customer.id is null then null else jsonb_build_object(
      'id', v_customer.id,
      'email', v_customer.email,
      'displayName', v_customer.display_name
    ) end,
    'payment', v_payment,
    'refundFacts', jsonb_build_object(
      'paymentTaken', (v_payment is not null and (v_payment->>'status') = 'paid'),
      'refundedAmount', v_refund_total::text,
      'latestRefundStatus', v_refund_status
    ),
    'telegram', jsonb_build_object(
      'staffGroup', case when v_staff_group.id is null then null else jsonb_build_object(
        'chatId', v_staff_group.telegram_chat_id,
        'chatTitle', v_staff_group.telegram_chat_title
      ) end,
      'businessOwners', v_owners
    ),
    'preferences', jsonb_build_object(
      'notifyOwnerOnCancellation', coalesce(v_notify_owner_on_cancellation, false)
    )
  );
end;
$function$;

-- ---------------------------------------------------------------------------
-- 4. New location-scoped context RPC, for events not tied to a single order
--    (store.paused/resumed, sales.daily_summary). Same "telegram" shape as
--    the order-context RPC so the dispatcher's planning context is uniform
--    regardless of which one produced it.
-- ---------------------------------------------------------------------------

create or replace function public.notifications_get_location_context(
  p_location_id uuid,
  p_summary_date date default null
)
returns jsonb
language plpgsql
stable
security definer
set search_path to ''
as $function$
declare
  v_location core.business_locations%rowtype;
  v_business core.businesses%rowtype;
  v_staff_group notifications.telegram_destinations%rowtype;
  v_owners jsonb;
  v_sales jsonb;
begin
  if not (select private.request_is_service_role()) then
    raise exception using errcode = '42501', message = 'service role required';
  end if;

  select l.* into v_location from core.business_locations l where l.id = p_location_id;
  if not found then
    raise exception using errcode = 'P0002', message = 'location not found';
  end if;
  select b.* into v_business from core.businesses b where b.id = v_location.business_id;

  select * into v_staff_group
  from notifications.telegram_destinations d
  where d.business_id = v_business.id
    and d.location_id = p_location_id
    and d.destination_type = 'staff_group'
    and d.is_active
  limit 1;

  select coalesce(jsonb_agg(jsonb_build_object('chatId', d.telegram_chat_id)), '[]'::jsonb)
  into v_owners
  from notifications.telegram_destinations d
  join core.business_users bu on bu.id = d.business_user_id
  where d.destination_type = 'business_user'
    and d.is_active
    and bu.business_id = v_business.id
    and bu.is_active
    and bu.role in ('owner', 'admin');

  if p_summary_date is not null then
    select jsonb_build_object(
      'date', p_summary_date,
      'orderCount', count(*) filter (where o.status <> 'cancelled'),
      'cancelledCount', count(*) filter (where o.status = 'cancelled'),
      'totalRevenue', coalesce(sum(o.grand_total) filter (where o.status <> 'cancelled'), 0)::text,
      'cashRevenue', coalesce(sum(o.grand_total) filter (where o.status <> 'cancelled' and o.payment_method = 'cash'), 0)::text,
      'onlineRevenue', coalesce(sum(o.grand_total) filter (where o.status <> 'cancelled' and o.payment_method = 'online'), 0)::text
    )
    into v_sales
    from ordering.orders o
    where o.location_id = p_location_id
      and (o.placed_at at time zone v_business.timezone)::date = p_summary_date;
  end if;

  return jsonb_build_object(
    'business', jsonb_build_object(
      'id', v_business.id, 'name', v_business.name, 'timezone', v_business.timezone, 'currency', v_business.currency
    ),
    'location', jsonb_build_object('id', v_location.id, 'name', v_location.name),
    'telegram', jsonb_build_object(
      'staffGroup', case when v_staff_group.id is null then null else jsonb_build_object(
        'chatId', v_staff_group.telegram_chat_id,
        'chatTitle', v_staff_group.telegram_chat_title
      ) end,
      'businessOwners', v_owners
    ),
    'salesSummary', v_sales
  );
end;
$function$;

revoke all on function public.notifications_get_location_context(uuid, date) from public;
revoke all on function public.notifications_get_location_context(uuid, date) from anon;
revoke all on function public.notifications_get_location_context(uuid, date) from authenticated;
grant execute on function public.notifications_get_location_context(uuid, date) to service_role;

-- ---------------------------------------------------------------------------
-- 5. Capture: store paused/resumed, from the existing ordering_enabled flag.
--    Same table this project already broadcasts from over Realtime -- this
--    just adds a second, independent trigger for the notification path.
-- ---------------------------------------------------------------------------

create or replace function private.capture_notification_event_from_ordering_status_change()
returns trigger
language plpgsql
security definer
set search_path to ''
as $function$
declare
  v_business_id uuid;
  v_event_type text;
begin
  if new.ordering_enabled is not distinct from old.ordering_enabled then
    return new;
  end if;

  select l.business_id into v_business_id from core.business_locations l where l.id = new.location_id;
  v_event_type := case when new.ordering_enabled then 'store.resumed' else 'store.paused' end;

  insert into notifications.events (
    event_type, entity_type, entity_id, business_id, location_id, dedupe_key, occurred_at, payload
  ) values (
    v_event_type, 'location', new.location_id, v_business_id, new.location_id,
    'location:' || new.location_id::text || ':' || v_event_type || ':' || extract(epoch from now())::text,
    now(), '{}'::jsonb
  )
  on conflict (dedupe_key) do nothing;

  return new;
end;
$function$;

drop trigger if exists restaurant_settings_capture_notification on ordering.restaurant_settings;
create trigger restaurant_settings_capture_notification
after update of ordering_enabled on ordering.restaurant_settings
for each row
when (old.ordering_enabled is distinct from new.ordering_enabled)
execute function private.capture_notification_event_from_ordering_status_change();

-- ---------------------------------------------------------------------------
-- 6. Capture: order.waiting_3m / order.waiting_8m. There is no state
--    transition to hang a trigger off -- "time has passed" is inherently a
--    poll -- so this is a periodic scan invoked directly by pg_cron
--    (no network I/O, same principle as the trigger-based captures: this
--    function only ever decides *whether an event happened*, never sends
--    anything itself). Idempotent via the same dedupe_key + ON CONFLICT
--    DO NOTHING pattern as every other capture path.
-- ---------------------------------------------------------------------------

create or replace function private.capture_waiting_order_notification_events()
returns void
language plpgsql
security definer
set search_path to ''
as $function$
begin
  insert into notifications.events (
    event_type, entity_type, entity_id, business_id, location_id, dedupe_key, occurred_at, payload
  )
  select
    'order.waiting_3m', 'order', o.id, o.business_id, o.location_id,
    'order:' || o.id::text || ':waiting_3m', now(),
    jsonb_build_object('schemaVersion', 1, 'orderId', o.id, 'customerId', o.customer_id, 'actorType', 'system', 'fromStatus', null, 'toStatus', 'placed')
  from ordering.orders o
  where o.status = 'placed' and o.placed_at <= now() - interval '3 minutes'
  on conflict (dedupe_key) do nothing;

  insert into notifications.events (
    event_type, entity_type, entity_id, business_id, location_id, dedupe_key, occurred_at, payload
  )
  select
    'order.waiting_8m', 'order', o.id, o.business_id, o.location_id,
    'order:' || o.id::text || ':waiting_8m', now(),
    jsonb_build_object('schemaVersion', 1, 'orderId', o.id, 'customerId', o.customer_id, 'actorType', 'system', 'fromStatus', null, 'toStatus', 'placed')
  from ordering.orders o
  where o.status = 'placed' and o.placed_at <= now() - interval '8 minutes'
  on conflict (dedupe_key) do nothing;
end;
$function$;

revoke all on function private.capture_waiting_order_notification_events() from public, anon, authenticated;

-- ---------------------------------------------------------------------------
-- 7. Capture: sales.daily_summary, once per business-local day at ~23:00.
--    dedupe_key is the business-local calendar date, so exactly one summary
--    event fires per location per day regardless of how often the sweep
--    runs within that hour.
-- ---------------------------------------------------------------------------

create or replace function private.capture_daily_sales_summary_notification_events()
returns void
language plpgsql
security definer
set search_path to ''
as $function$
begin
  insert into notifications.events (
    event_type, entity_type, entity_id, business_id, location_id, dedupe_key, occurred_at, payload
  )
  select
    'sales.daily_summary', 'location', l.id, l.business_id, l.id,
    'location:' || l.id::text || ':summary:' || to_char((now() at time zone b.timezone)::date, 'YYYY-MM-DD'),
    now(),
    jsonb_build_object('summaryDate', to_char((now() at time zone b.timezone)::date, 'YYYY-MM-DD'))
  from core.business_locations l
  join core.businesses b on b.id = l.business_id
  where l.is_active
    and extract(hour from (now() at time zone b.timezone))::int = 23
  on conflict (dedupe_key) do nothing;
end;
$function$;

revoke all on function private.capture_daily_sales_summary_notification_events() from public, anon, authenticated;

-- ---------------------------------------------------------------------------
-- 8. Cron sweeps. Pure SQL, no HTTP -- these only ever decide whether an
--    event happened; the existing notification-dispatcher sweep (already
--    scheduled) is what actually sends.
-- ---------------------------------------------------------------------------

select cron.schedule(
  'waiting-order-events-sweep', '* * * * *', $$select private.capture_waiting_order_notification_events();$$
) where not exists (select 1 from cron.job where jobname = 'waiting-order-events-sweep');

select cron.schedule(
  'daily-sales-summary-sweep', '*/15 * * * *', $$select private.capture_daily_sales_summary_notification_events();$$
) where not exists (select 1 from cron.job where jobname = 'daily-sales-summary-sweep');
